// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVw2LiEZ68cSA_DQhokpJm-JiJvb4M370',
    appId: '1:137683341759:web:7892c5d2c9f78903a7d10a',
    messagingSenderId: '137683341759',
    projectId: 'attendance-app-32fc0',
    authDomain: 'attendance-app-32fc0.firebaseapp.com',
    storageBucket: 'attendance-app-32fc0.appspot.com',
    measurementId: 'G-SGGJSNN7RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe4V6fzkUy-x30Wz8MaRVmJKTj-mN4CtI',
    appId: '1:137683341759:android:ee94189837ad49cea7d10a',
    messagingSenderId: '137683341759',
    projectId: 'attendance-app-32fc0',
    storageBucket: 'attendance-app-32fc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbnv6S0REcqKtZV7HpC2FPpv7cJ1J38nE',
    appId: '1:137683341759:ios:950205509e464095a7d10a',
    messagingSenderId: '137683341759',
    projectId: 'attendance-app-32fc0',
    storageBucket: 'attendance-app-32fc0.appspot.com',
    iosBundleId: 'com.team.attendienceApp',
  );
}
